- hosts: vps
  roles:
    - deploy
  # tasks:
  #   - name: Ensure the project directory exists
  #     file:
  #       path: /root/skinsoko_project
  #       state: directory

  #   - name: Pull the latest code from the repository
  #     git:
  #       repo: 'https://github.com/Bot-on-Tapwater/skinsoko_project.git'
  #       dest: '/root/skinsoko_project'
  #       version: 'master'
  #       force: yes

  #   # - name: Install Python dependencies
  #   #   pip:
  #   #     requirements: /root/skinsoko_project/requirements.txt
  #   #     virtualenv: /root/skinsoko_project/myvenv

  #   # - name: Apply database migrations
  #   #   command: source /root/skinsoko_project/myvenv/bin/activate && python manage.py migrate
  #   #   args:
  #   #     chdir: /root/skinsoko_project

  #   # - name: Collect static files
  #   #   command: source /root/skinsoko_project/myvenv/bin/activate && python manage.py collectstatic --noinput
  #   #   args:
  #   #     chdir: /root/skinsoko_project

  #   - name: Restart skinsoko service
  #     systemd:
  #       name: skinsoko
  #       state: restarted
