name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 78.111.67.122 >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'  # Optional: Disable host key checking if you're testing
        ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key
      run: |
        ansible-playbook -i hosts deploy.yml
